import type { Opportunity } from './opportunities/opportunity.entity';

type OpportunitySeed = Omit<Opportunity, 'id'>;

export type OpportunitySkillLink = {
  opportunityTitle: string;
  required: boolean;
  skillSlugs: string[];
};

export const OPPORTUNITIES: OpportunitySeed[] = [
  // ═══════════════════════ EMPLEOS (23) ═══════════════════════
  {
    title: 'Practicante de soporte técnico de redes',
    organization: 'Cartagena Tech Solutions',
    kind: 'empleo',
    requirements: [
      'Cursando técnico/tecnólogo en sistemas',
      'Conocimientos básicos de redes',
      'Disponibilidad jornada mañana',
    ],
    slotsTotal: 5,
    slotsAvailable: 2,
    barrio: 'El Pozón',
    modalidad: 'hibrido',
    interests: ['tecnologia'],
  },
  {
    title: 'Auxiliar de recepción turística bilingüe',
    organization: 'Hotel Las Américas — Turismo Cartagena',
    kind: 'empleo',
    requirements: ['Bachiller', 'Inglés conversacional básico', 'Disponibilidad fines de semana'],
    slotsTotal: 8,
    slotsAvailable: 3,
    barrio: 'Bocagrande',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'liderazgo'],
  },
  {
    title: 'Operario de bodega y logística',
    organization: 'Almacenes Éxito — El Pozón',
    kind: 'empleo',
    requirements: ['Bachiller', 'Disponibilidad turnos rotativos', 'Manejo básico de Excel'],
    slotsTotal: 12,
    slotsAvailable: 5,
    barrio: 'El Pozón',
    modalidad: 'presencial',
    interests: ['emprendimiento'],
  },
  {
    title: 'Asistente administrativo',
    organization: 'Alcaldía Distrital de Cartagena',
    kind: 'empleo',
    requirements: ['Bachiller', 'Excel intermedio', 'Redacción de documentos'],
    slotsTotal: 6,
    slotsAvailable: 1,
    barrio: 'Centro Histórico',
    modalidad: 'presencial',
    interests: ['liderazgo', 'emprendimiento'],
  },
  {
    title: 'Repartidor/a de domicilios',
    organization: 'Rappi — Cartagena',
    kind: 'empleo',
    requirements: ['Mayor de 18 años', 'Bicicleta o moto propia', 'Conocimiento de la ciudad'],
    slotsTotal: 40,
    slotsAvailable: 22,
    barrio: 'Olaya Herrera',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'deporte'],
  },
  {
    title: 'Auxiliar de cocina',
    organization: 'Restaurante La Mulata — Getsemaní',
    kind: 'empleo',
    requirements: ['Experiencia básica en cocina', 'Disponibilidad noche y fines de semana'],
    slotsTotal: 4,
    slotsAvailable: 2,
    barrio: 'Getsemaní',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'arte'],
  },
  {
    title: 'Diseñador gráfico junior',
    organization: 'Agencia Caribe Digital',
    kind: 'empleo',
    requirements: ['Portafolio básico', 'Canva o Photoshop', 'Creatividad'],
    slotsTotal: 3,
    slotsAvailable: 1,
    barrio: 'Manga',
    modalidad: 'virtual',
    interests: ['arte', 'tecnologia'],
  },
  {
    title: 'Técnico en mantenimiento de equipos de cómputo',
    organization: 'Informática Popular — Manga',
    kind: 'empleo',
    requirements: ['Diagnóstico de hardware', 'Instalación de software', 'Atención al usuario'],
    slotsTotal: 4,
    slotsAvailable: 2,
    barrio: 'Manga',
    modalidad: 'presencial',
    interests: ['tecnologia'],
  },
  {
    title: 'Agente de call center bilingüe',
    organization: 'Teleperformance — Cartagena',
    kind: 'empleo',
    requirements: ['Bachiller', 'Inglés B1 mínimo', 'Internet estable en casa'],
    slotsTotal: 30,
    slotsAvailable: 14,
    barrio: 'Crespo',
    modalidad: 'virtual',
    interests: ['tecnologia', 'emprendimiento'],
  },
  {
    title: 'Auxiliar de enfermería',
    organization: 'Clínica Bocagrande',
    kind: 'empleo',
    requirements: ['Técnico en salud o estudiante', 'Disponibilidad turnos'],
    slotsTotal: 6,
    slotsAvailable: 2,
    barrio: 'Bocagrande',
    modalidad: 'presencial',
    interests: ['liderazgo', 'deporte'],
  },
  {
    title: 'Conductor/a de entregas locales',
    organization: 'D1 — San Fernando',
    kind: 'empleo',
    requirements: ['Licencia de conducción', 'Conocimiento zona sur', 'Puntualidad'],
    slotsTotal: 10,
    slotsAvailable: 4,
    barrio: 'San Fernando',
    modalidad: 'presencial',
    interests: ['emprendimiento'],
  },
  {
    title: 'Community manager',
    organization: 'Startup Caribe Labs',
    kind: 'empleo',
    requirements: ['Redes sociales', 'Redacción creativa', 'Canva básico'],
    slotsTotal: 2,
    slotsAvailable: 1,
    barrio: 'Getsemaní',
    modalidad: 'virtual',
    interests: ['emprendimiento', 'arte', 'tecnologia'],
  },
  {
    title: 'Ayudante de obra civil',
    organization: 'Constructora Bolívar Sur',
    kind: 'empleo',
    requirements: ['Mayor de 18 años', 'Disponibilidad campo', 'Trabajo en equipo'],
    slotsTotal: 20,
    slotsAvailable: 11,
    barrio: 'Blas de Lezo',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'deporte'],
  },
  {
    title: 'Cajero/a de servicios bancarios',
    organization: 'Bancolombia — Torices',
    kind: 'empleo',
    requirements: ['Bachiller', 'Atención al cliente', 'Manejo de caja'],
    slotsTotal: 4,
    slotsAvailable: 0,
    barrio: 'Torices',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'liderazgo'],
  },
  {
    title: 'Fotógrafo/a de eventos sociales',
    organization: 'Estudio Luz Caribe',
    kind: 'empleo',
    requirements: ['Manejo de cámara réflex', 'Edición básica', 'Portafolio'],
    slotsTotal: 3,
    slotsAvailable: 2,
    barrio: 'Getsemaní',
    modalidad: 'presencial',
    interests: ['arte'],
  },
  {
    title: 'Instructor/a de fitness',
    organization: 'Smart Fit — Bocagrande',
    kind: 'empleo',
    requirements: ['Certificación entrenamiento', 'Comunicación', 'Disponibilidad tarde-noche'],
    slotsTotal: 5,
    slotsAvailable: 2,
    barrio: 'Bocagrande',
    modalidad: 'presencial',
    interests: ['deporte', 'liderazgo'],
  },
  {
    title: 'Asistente de ventas retail',
    organization: 'Falabella — Pie de la Popa',
    kind: 'empleo',
    requirements: ['Bachiller', 'Orientación al cliente', 'Fines de semana'],
    slotsTotal: 15,
    slotsAvailable: 7,
    barrio: 'Pie de la Popa',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'liderazgo'],
  },
  {
    title: 'Auxiliar de laboratorio escolar',
    organization: 'Colegio Técnico Chiquinquirá',
    kind: 'empleo',
    requirements: ['Estudiante o recién graduado en ciencias', 'Organización'],
    slotsTotal: 2,
    slotsAvailable: 1,
    barrio: 'Chiquinquirá',
    modalidad: 'presencial',
    interests: ['tecnologia', 'liderazgo'],
  },
  {
    title: 'Operador/a telefónico — soporte TI',
    organization: 'HelpDesk Caribe',
    kind: 'empleo',
    requirements: ['Lógica de programación básica', 'Inglés técnico', 'Turnos rotativos'],
    slotsTotal: 8,
    slotsAvailable: 3,
    barrio: 'Manga',
    modalidad: 'hibrido',
    interests: ['tecnologia'],
  },
  {
    title: 'Montaje de eventos y escenarios',
    organization: 'Centro de Convenciones Cartagena',
    kind: 'empleo',
    requirements: ['Fuerza física', 'Trabajo en equipo', 'Disponibilidad eventos'],
    slotsTotal: 12,
    slotsAvailable: 6,
    barrio: 'Centro Histórico',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'arte'],
  },
  {
    title: 'Auxiliar de biblioteca municipal',
    organization: 'Biblioteca Distrital — San Fernando',
    kind: 'empleo',
    requirements: ['Bachiller', 'Amor por la lectura', 'Organización de archivos'],
    slotsTotal: 3,
    slotsAvailable: 2,
    barrio: 'San Fernando',
    modalidad: 'presencial',
    interests: ['arte', 'liderazgo'],
  },
  {
    title: 'Técnico en aire acondicionado',
    organization: 'Clima Caribe SAS',
    kind: 'empleo',
    requirements: ['Curso técnico en refrigeración', 'Licencia de conducción'],
    slotsTotal: 4,
    slotsAvailable: 2,
    barrio: 'Olaya Herrera',
    modalidad: 'presencial',
    interests: ['tecnologia', 'emprendimiento'],
  },
  {
    title: 'Mesero/a — hotel cinco estrellas',
    organization: 'Hilton Cartagena',
    kind: 'empleo',
    requirements: ['Inglés básico', 'Actitud de servicio', 'Disponibilidad rotativa'],
    slotsTotal: 10,
    slotsAvailable: 4,
    barrio: 'Manga',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'liderazgo'],
  },

  // ═══════════════════════ ESTUDIOS (22) ═══════════════════════
  {
    title: 'Técnico laboral en Redes de Datos — SENA El Pozón',
    organization: 'SENA Regional Bolívar — El Pozón',
    kind: 'estudio',
    requirements: ['Bachiller', 'Prueba de aptitud SENA', 'Disponibilidad tiempo completo'],
    slotsTotal: 35,
    slotsAvailable: 0,
    barrio: 'El Pozón',
    modalidad: 'presencial',
    interests: ['tecnologia'],
  },
  {
    title: 'Tecnólogo en Análisis y Desarrollo de Software',
    organization: 'SENA Regional Bolívar — Cartagena',
    kind: 'estudio',
    requirements: ['Bachiller', 'Prueba de aptitud SENA', 'Disponibilidad tiempo completo'],
    slotsTotal: 30,
    slotsAvailable: 4,
    barrio: 'Chiquinquirá',
    modalidad: 'virtual',
    interests: ['tecnologia', 'emprendimiento'],
  },
  {
    title: 'Tecnólogo en Análisis y Desarrollo de Software — jornada El Pozón',
    organization: 'SENA Regional Bolívar — El Pozón',
    kind: 'estudio',
    requirements: ['Bachiller', 'Residir en zona sur de Cartagena', 'Tiempo completo'],
    slotsTotal: 25,
    slotsAvailable: 3,
    barrio: 'El Pozón',
    modalidad: 'presencial',
    interests: ['tecnologia', 'emprendimiento'],
  },
  {
    title: 'Curso técnico de inglés para servicios turísticos',
    organization: 'SENA Regional Bolívar — Cartagena',
    kind: 'estudio',
    requirements: ['Bachillerato en curso o bachiller', 'Disponibilidad jornada tarde'],
    slotsTotal: 40,
    slotsAvailable: 9,
    barrio: 'Getsemaní',
    modalidad: 'hibrido',
    interests: ['emprendimiento', 'liderazgo'],
  },
  {
    title: 'Técnico en Contabilidad y Finanzas',
    organization: 'SENA — Olaya Herrera',
    kind: 'estudio',
    requirements: ['Bachiller', 'Matemáticas básicas', 'Jornada mañana'],
    slotsTotal: 28,
    slotsAvailable: 6,
    barrio: 'Olaya Herrera',
    modalidad: 'presencial',
    interests: ['emprendimiento'],
  },
  {
    title: 'Curso corto Excel para empleabilidad',
    organization: 'SENA — Chiquinquirá',
    kind: 'estudio',
    requirements: ['Bachiller', 'Interés en oficina y administración'],
    slotsTotal: 50,
    slotsAvailable: 14,
    barrio: 'Chiquinquirá',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'tecnologia'],
  },
  {
    title: 'Técnico en Turismo y Guianza',
    organization: 'Universidad de Cartagena — Centro',
    kind: 'estudio',
    requirements: ['Bachiller', 'Inglés básico deseable'],
    slotsTotal: 20,
    slotsAvailable: 7,
    barrio: 'Centro Histórico',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'liderazgo'],
  },
  {
    title: 'Diplomado en Marketing Digital',
    organization: 'SENA + Platzi — Cartagena',
    kind: 'estudio',
    requirements: ['Mayor de 16 años', 'Acceso a internet'],
    slotsTotal: 60,
    slotsAvailable: 18,
    barrio: 'Bocagrande',
    modalidad: 'virtual',
    interests: ['emprendimiento', 'tecnologia'],
  },
  {
    title: 'Técnico en Electricidad Industrial',
    organization: 'SENA — La Boquilla',
    kind: 'estudio',
    requirements: ['Bachiller', 'Disponibilidad tiempo completo'],
    slotsTotal: 22,
    slotsAvailable: 4,
    barrio: 'La Boquilla',
    modalidad: 'presencial',
    interests: ['tecnologia'],
  },
  {
    title: 'Bachillerato Plus nocturno para jóvenes trabajadores',
    organization: 'I.E. Nelson Mandela',
    kind: 'estudio',
    requirements: ['Mayor de 15 años', 'Disponibilidad noche'],
    slotsTotal: 45,
    slotsAvailable: 11,
    barrio: 'Nelson Mandela',
    modalidad: 'presencial',
    interests: ['liderazgo', 'deporte'],
  },
  {
    title: 'Técnico en Gestión Administrativa',
    organization: 'SENA — Crespo',
    kind: 'estudio',
    requirements: ['Bachiller', 'Jornada mañana o tarde'],
    slotsTotal: 32,
    slotsAvailable: 8,
    barrio: 'Crespo',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'liderazgo'],
  },
  {
    title: 'Técnico en Producción Agropecuaria Ecológica',
    organization: 'SENA — La Boquilla',
    kind: 'estudio',
    requirements: ['Bachiller', 'Interés en campo y sostenibilidad'],
    slotsTotal: 18,
    slotsAvailable: 5,
    barrio: 'La Boquilla',
    modalidad: 'presencial',
    interests: ['medio-ambiente', 'emprendimiento'],
  },
  {
    title: 'Curso corto bartender y coctelería',
    organization: 'SENA — Getsemaní',
    kind: 'estudio',
    requirements: ['Mayor de 18 años', 'Disponibilidad noche'],
    slotsTotal: 24,
    slotsAvailable: 10,
    barrio: 'Getsemaní',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'arte'],
  },
  {
    title: 'Técnico en Peluquería y Estética Integral',
    organization: 'SENA — Pie de la Popa',
    kind: 'estudio',
    requirements: ['Bachiller', 'Creatividad y manualidad'],
    slotsTotal: 20,
    slotsAvailable: 6,
    barrio: 'Pie de la Popa',
    modalidad: 'presencial',
    interests: ['arte', 'emprendimiento'],
  },
  {
    title: 'Preuniversitario gratuito ICFES',
    organization: 'Secretaría de Educación — Torices',
    kind: 'estudio',
    requirements: ['Grado 10 u 11', 'Compromiso de asistencia'],
    slotsTotal: 80,
    slotsAvailable: 25,
    barrio: 'Torices',
    modalidad: 'presencial',
    interests: ['liderazgo', 'tecnologia'],
  },
  {
    title: 'Técnico en Mecánica Automotriz',
    organization: 'SENA — Blas de Lezo',
    kind: 'estudio',
    requirements: ['Bachiller', 'Tiempo completo'],
    slotsTotal: 26,
    slotsAvailable: 7,
    barrio: 'Blas de Lezo',
    modalidad: 'presencial',
    interests: ['tecnologia', 'emprendimiento'],
  },
  {
    title: 'Curso certificado primeros auxilios',
    organization: 'Cruz Roja — Cartagena',
    kind: 'estudio',
    requirements: ['Mayor de 16 años', '8 sesiones presenciales'],
    slotsTotal: 40,
    slotsAvailable: 15,
    barrio: 'Manga',
    modalidad: 'hibrido',
    interests: ['liderazgo', 'deporte'],
  },
  {
    title: 'Técnico en Cocina y Gastronomía',
    organization: 'SENA — San Fernando',
    kind: 'estudio',
    requirements: ['Bachiller', 'Higiene alimentaria básica'],
    slotsTotal: 22,
    slotsAvailable: 5,
    barrio: 'San Fernando',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'arte'],
  },
  {
    title: 'Programa jóvenes investigadores STEM',
    organization: 'Universidad de Cartagena',
    kind: 'estudio',
    requirements: ['Estudiante universitario o recién graduado', 'Inglés técnico'],
    slotsTotal: 15,
    slotsAvailable: 4,
    barrio: 'Centro Histórico',
    modalidad: 'virtual',
    interests: ['tecnologia', 'liderazgo'],
  },
  {
    title: 'Técnico en Gestión de Proyectos',
    organization: 'SENA — modalidad virtual',
    kind: 'estudio',
    requirements: ['Bachiller', 'Acceso a internet'],
    slotsTotal: 35,
    slotsAvailable: 12,
    barrio: 'Bocagrande',
    modalidad: 'virtual',
    interests: ['liderazgo', 'emprendimiento'],
  },
  {
    title: 'Escuela de música popular caribeña',
    organization: 'Conservatorio de Cartagena',
    kind: 'estudio',
    requirements: ['Mayor de 14 años', 'Audición básica'],
    slotsTotal: 30,
    slotsAvailable: 9,
    barrio: 'Getsemaní',
    modalidad: 'presencial',
    interests: ['arte', 'liderazgo'],
  },
  {
    title: 'Técnico en Confección Industrial',
    organization: 'SENA — Nelson Mandela',
    kind: 'estudio',
    requirements: ['Bachiller', 'Jornada mañana'],
    slotsTotal: 24,
    slotsAvailable: 8,
    barrio: 'Nelson Mandela',
    modalidad: 'presencial',
    interests: ['arte', 'emprendimiento'],
  },
  {
    title: 'Curso introductorio en ciberseguridad',
    organization: 'Cámara de Comercio de Cartagena',
    kind: 'estudio',
    requirements: ['Conocimientos básicos de redes', 'Acceso a PC'],
    slotsTotal: 45,
    slotsAvailable: 20,
    barrio: 'Chiquinquirá',
    modalidad: 'virtual',
    interests: ['tecnologia'],
  },

  // ═══════════════════════ VOLUNTARIADOS (18) ═══════════════════════
  {
    title: 'Tallerista de liderazgo juvenil comunitario',
    organization: 'Fundación Mi Sangre',
    kind: 'voluntariado',
    requirements: ['Mayor de 16 años', 'Habilidades de comunicación', '4 horas semanales'],
    slotsTotal: 20,
    slotsAvailable: 12,
    barrio: 'El Pozón',
    modalidad: 'presencial',
    interests: ['liderazgo', 'arte'],
  },
  {
    title: 'Brigada de recuperación de la Ciénaga de la Virgen',
    organization: 'Fundación Mi Sangre',
    kind: 'voluntariado',
    requirements: ['Mayor de 15 años', 'Fines de semana', 'Interés en medio ambiente'],
    slotsTotal: 30,
    slotsAvailable: 18,
    barrio: 'La Boquilla',
    modalidad: 'presencial',
    interests: ['medio-ambiente', 'liderazgo'],
  },
  {
    title: 'Mentoría de lectura en biblioteca comunitaria',
    organization: 'Biblioteca Distrital — El Bosque',
    kind: 'voluntariado',
    requirements: ['Mayor de 16 años', 'Paciencia con niños', '2 horas semanales'],
    slotsTotal: 15,
    slotsAvailable: 8,
    barrio: 'El Bosque',
    modalidad: 'presencial',
    interests: ['arte', 'liderazgo'],
  },
  {
    title: 'Escuela de fútbol comunitaria',
    organization: 'IDRD Cartagena — Nelson Mandela',
    kind: 'voluntariado',
    requirements: ['Mayor de 15 años', 'Trabajo en equipo', 'Fines de semana'],
    slotsTotal: 25,
    slotsAvailable: 15,
    barrio: 'Nelson Mandela',
    modalidad: 'presencial',
    interests: ['deporte', 'liderazgo'],
  },
  {
    title: 'Red juvenil de primeros auxilios',
    organization: 'Cruz Roja Colombiana — Cartagena',
    kind: 'voluntariado',
    requirements: ['Mayor de 16 años', 'Compromiso de 6 meses'],
    slotsTotal: 18,
    slotsAvailable: 10,
    barrio: 'Manga',
    modalidad: 'hibrido',
    interests: ['liderazgo', 'deporte'],
  },
  {
    title: 'Huerta urbana comunitaria',
    organization: 'Corporación Sembrando Futuro',
    kind: 'voluntariado',
    requirements: ['Interés en agricultura urbana', 'Fines de semana'],
    slotsTotal: 12,
    slotsAvailable: 6,
    barrio: 'Olaya Herrera',
    modalidad: 'presencial',
    interests: ['medio-ambiente', 'emprendimiento'],
  },
  {
    title: 'Murales comunitarios — arte urbano',
    organization: 'Colectivo Mural Caribe',
    kind: 'voluntariado',
    requirements: ['Creatividad', 'Trabajo en altura con supervisión', 'Fines de semana'],
    slotsTotal: 16,
    slotsAvailable: 9,
    barrio: 'Getsemaní',
    modalidad: 'presencial',
    interests: ['arte', 'liderazgo'],
  },
  {
    title: 'Apoyo escuelas deportivas barriales',
    organization: 'IDRD — El Pozón',
    kind: 'voluntariado',
    requirements: ['Mayor de 15 años', 'Deporte o recreación', 'Tardes'],
    slotsTotal: 22,
    slotsAvailable: 14,
    barrio: 'El Pozón',
    modalidad: 'presencial',
    interests: ['deporte', 'liderazgo'],
  },
  {
    title: 'Banco de alimentos comunitario',
    organization: 'Fundación Amigos del Barrio',
    kind: 'voluntariado',
    requirements: ['Organización', 'Empatía', 'Sábados en la mañana'],
    slotsTotal: 20,
    slotsAvailable: 11,
    barrio: 'San Fernando',
    modalidad: 'presencial',
    interests: ['medio-ambiente', 'liderazgo'],
  },
  {
    title: 'Brigada de reforestación urbana',
    organization: 'Corporación Verde Cartagena',
    kind: 'voluntariado',
    requirements: ['Mayor de 14 años', 'Trabajo al sol', 'Fines de semana'],
    slotsTotal: 28,
    slotsAvailable: 16,
    barrio: 'Blas de Lezo',
    modalidad: 'presencial',
    interests: ['medio-ambiente'],
  },
  {
    title: 'Taller de emprendimiento para mujeres jóvenes',
    organization: 'SENA Emprende — Olaya Herrera',
    kind: 'voluntariado',
    requirements: ['Facilitación grupal', 'Comunicación', '3 horas semanales'],
    slotsTotal: 14,
    slotsAvailable: 7,
    barrio: 'Olaya Herrera',
    modalidad: 'presencial',
    interests: ['emprendimiento', 'liderazgo'],
  },
  {
    title: 'Voluntariado hospital infantil',
    organization: 'Hospital Naval de Bocagrande',
    kind: 'voluntariado',
    requirements: ['Mayor de 17 años', 'Certificado de buena conducta', 'Empatía'],
    slotsTotal: 10,
    slotsAvailable: 3,
    barrio: 'Bocagrande',
    modalidad: 'presencial',
    interests: ['liderazgo', 'arte'],
  },
  {
    title: 'Guardaplayas juvenil — temporada alta',
    organization: 'Invemar + Alcaldía',
    kind: 'voluntariado',
    requirements: ['Natación básica', 'Primeros auxilios deseable', 'Fines de semana'],
    slotsTotal: 24,
    slotsAvailable: 12,
    barrio: 'La Boquilla',
    modalidad: 'presencial',
    interests: ['medio-ambiente', 'deporte'],
  },
  {
    title: 'Club de lectura virtual BibloRed',
    organization: 'Red Nacional de Bibliotecas',
    kind: 'voluntariado',
    requirements: ['Internet', 'Facilitación de lectura', '1 hora semanal'],
    slotsTotal: 50,
    slotsAvailable: 30,
    barrio: 'Centro Histórico',
    modalidad: 'virtual',
    interests: ['arte', 'liderazgo'],
  },
  {
    title: 'Mentores STEM en escuelas públicas',
    organization: 'MinTIC + Secretaría de Educación',
    kind: 'voluntariado',
    requirements: ['Conocimientos en programación o robótica', 'Comunicación'],
    slotsTotal: 30,
    slotsAvailable: 18,
    barrio: 'El Pozón',
    modalidad: 'hibrido',
    interests: ['tecnologia', 'liderazgo'],
  },
  {
    title: 'Festival de danza popular del Caribe',
    organization: 'Instituto de Cultura de Bolívar',
    kind: 'voluntariado',
    requirements: ['Baile o producción cultural', 'Disponibilidad ensayos'],
    slotsTotal: 35,
    slotsAvailable: 20,
    barrio: 'Pie de la Popa',
    modalidad: 'presencial',
    interests: ['arte', 'deporte'],
  },
  {
    title: 'Campaña de bienestar animal',
    organization: 'Fundación Patitas Cartagena',
    kind: 'voluntariado',
    requirements: ['Amor por los animales', 'Fines de semana'],
    slotsTotal: 18,
    slotsAvailable: 10,
    barrio: 'Crespo',
    modalidad: 'presencial',
    interests: ['medio-ambiente', 'liderazgo'],
  },
  {
    title: 'Jornada digital para adultos mayores',
    organization: 'Punto Vive Digital — Chiquinquirá',
    kind: 'voluntariado',
    requirements: ['Paciencia', 'Manejo básico de celular y PC', 'Comunicación'],
    slotsTotal: 12,
    slotsAvailable: 5,
    barrio: 'Chiquinquirá',
    modalidad: 'presencial',
    interests: ['tecnologia', 'liderazgo'],
  },
];

export const OPPORTUNITY_SKILLS: OpportunitySkillLink[] = [
  { opportunityTitle: 'Practicante de soporte técnico de redes', required: true, skillSlugs: ['redes', 'logica-programacion'] },
  { opportunityTitle: 'Auxiliar de recepción turística bilingüe', required: true, skillSlugs: ['ingles-conversacional', 'atencion-cliente'] },
  { opportunityTitle: 'Operario de bodega y logística', required: true, skillSlugs: ['excel-avanzado'] },
  { opportunityTitle: 'Asistente administrativo', required: true, skillSlugs: ['excel-avanzado', 'comunicacion'] },
  { opportunityTitle: 'Diseñador gráfico junior', required: true, skillSlugs: ['comunicacion'] },
  { opportunityTitle: 'Técnico en mantenimiento de equipos de cómputo', required: true, skillSlugs: ['logica-programacion', 'atencion-cliente'] },
  { opportunityTitle: 'Agente de call center bilingüe', required: true, skillSlugs: ['ingles-conversacional', 'comunicacion'] },
  { opportunityTitle: 'Auxiliar de enfermería', required: true, skillSlugs: ['comunicacion', 'atencion-cliente'] },
  { opportunityTitle: 'Community manager', required: true, skillSlugs: ['comunicacion'] },
  { opportunityTitle: 'Cajero/a de servicios bancarios', required: true, skillSlugs: ['atencion-cliente', 'excel-avanzado'] },
  { opportunityTitle: 'Operador/a telefónico — soporte TI', required: true, skillSlugs: ['logica-programacion', 'ingles-tecnico', 'atencion-cliente'] },
  { opportunityTitle: 'Técnico en aire acondicionado', required: true, skillSlugs: ['redes'] },
  { opportunityTitle: 'Mesero/a — hotel cinco estrellas', required: true, skillSlugs: ['ingles-conversacional', 'atencion-cliente'] },
  { opportunityTitle: 'Técnico laboral en Redes de Datos — SENA El Pozón', required: false, skillSlugs: ['redes', 'logica-programacion'] },
  { opportunityTitle: 'Tecnólogo en Análisis y Desarrollo de Software', required: false, skillSlugs: ['logica-programacion', 'bases-datos', 'redes'] },
  { opportunityTitle: 'Tecnólogo en Análisis y Desarrollo de Software — jornada El Pozón', required: false, skillSlugs: ['logica-programacion', 'bases-datos', 'redes'] },
  { opportunityTitle: 'Curso técnico de inglés para servicios turísticos', required: false, skillSlugs: ['ingles-tecnico', 'ingles-conversacional'] },
  { opportunityTitle: 'Curso corto Excel para empleabilidad', required: false, skillSlugs: ['excel-avanzado'] },
  { opportunityTitle: 'Técnico en Gestión Administrativa', required: false, skillSlugs: ['excel-avanzado', 'comunicacion'] },
  { opportunityTitle: 'Curso introductorio en ciberseguridad', required: false, skillSlugs: ['redes', 'logica-programacion'] },
  { opportunityTitle: 'Programa jóvenes investigadores STEM', required: false, skillSlugs: ['bases-datos', 'ingles-tecnico'] },
  { opportunityTitle: 'Tallerista de liderazgo juvenil comunitario', required: false, skillSlugs: ['comunicacion'] },
  { opportunityTitle: 'Brigada de recuperación de la Ciénaga de la Virgen', required: false, skillSlugs: ['educacion-ambiental'] },
  { opportunityTitle: 'Mentores STEM en escuelas públicas', required: false, skillSlugs: ['logica-programacion', 'comunicacion'] },
  { opportunityTitle: 'Murales comunitarios — arte urbano', required: false, skillSlugs: ['comunicacion'] },
  { opportunityTitle: 'Huerta urbana comunitaria', required: false, skillSlugs: ['educacion-ambiental'] },
];

export const PITCH_DEMO = {
  mariaName: 'María Torres',
  practicanteTitle: 'Practicante de soporte técnico de redes',
  fullCourseTitle: 'Técnico laboral en Redes de Datos — SENA El Pozón',
  waitlistTarget: 47,
} as const;
